name: Deploy Flask Lambda

on:
  push:
    branches:
      - main  # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.126.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # or your region

      - name: Install dependencies into .aws-sam/build directory
        run: |
          mkdir -p .aws-sam/build/FlaskFunction
          pip install -r requirements.txt -t .aws-sam/build/FlaskFunction

      - name: Copy app and template
        run: |
          cp app.py .aws-sam/build/FlaskFunction/
          cp template.yaml .aws-sam/build/template.yaml

      - name: Deploy with SAM
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name flask-lambda-awsgi \
            --capabilities CAPABILITY_IAM \
            --region ap-southeast-2 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
